[package]
name = "deno_iced"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
iced = "0.3"
num-traits = "0.2"
num-derive = "0.3"
rand = "0.8.4"
iced_futures = "0.3"
futures = "0.3.17"
lazy_static = "1.4.0"