[package]
name = "deno_iced"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
iced = { version = "0.3", features = [] }
num-traits = "0.2"
num-derive = "0.3"
rand = "0.8.4"